Repository nishiki-tech/nishiki-documents, pull requests merged in 2023-10, with the labels that each got.

#8 Feature/2 add project documnent
  .gitignore
  project-document/.gitignore
  project-document/README.md
  project-document/babel.config.js
  project-document/docs/intro.md
  project-document/docusaurus.config.js
  project-document/package-lock.json
  project-document/package.json
  project-document/sidebars.js
  project-document/src/components/HomepageFeatures/index.tsx
  project-document/src/components/HomepageFeatures/styles.module.css
  project-document/src/css/custom.css
  project-document/static/.nojekyll
  project-document/static/img/docusaurus-social-card.jpg
  project-document/static/img/docusaurus.png
  project-document/static/img/favicon.ico
  project-document/static/img/logo.svg
  project-document/static/img/undraw_docusaurus_mountain.svg
  project-document/static/img/undraw_docusaurus_react.svg
  project-document/static/img/undraw_docusaurus_tree.svg
  project-document/tsconfig.json
Labels: documentation

#11 Feature/creationg domain model
  project-document/bun.lockb
  project-document/docs/domain-model/domain-model.md
  project-document/docs/er-diagram/er-diagram.md
  project-document/docusaurus.config.js
  project-document/package.json
  project-document/sidebars.js
Labels: documentation

#13 fix change the project document runtime
  project-document/README.md
  project-document/bun.lockb
  project-document/package-lock.json
Labels: bug

#14 Feature/10 create a swagger document
  web-api/nishiki-web-api.yaml
Labels: documentation

#23 21 update user context document
  project-document/docs/domain-model/domain-model.md
  project-document/docs/domain-model/user-context/user.md
  project-document/sidebars.js
Labels: documentation, enhancement

#27 Add issue and pull request templates, CONTRIBUTION.md
  .github/ISSUE_TEMPLATE/enhancement_comunity.md
  .github/ISSUE_TEMPLATE/enhancement_team.md
  .github/ISSUE_TEMPLATE/problem_comunity.md
  .github/ISSUE_TEMPLATE/problem_team.md
  .github/ISSUE_TEMPLATE/question_comunity.md
  .github/ISSUE_TEMPLATE/question_team.md
  .github/PULL_REQUEST_TEMPLATE/community.md
  .github/PULL_REQUEST_TEMPLATE/team.md
  docs/CONTRIBUTING.md
Labels: documentation, internal

#29 fix: added a lower limit
  project-document/docs/domain-model/user-context/user.md
Labels: bug, documentation

#30 update: Expire -> Expiry
  project-document/docs/domain-model/domain-model.md
Labels: documentation

#35 feat: updated the welcome page
  project-document/docs/intro.md
Labels: documentation, enhancement
