Repository nishiki-tech/nishiki-documents, pull requests merged in 2023-12, with the labels that each got.

#63 updated the group model
  web-api/nishiki-web-api.yaml
Labels: documentation

#64 added a list of users in the group API
  web-api/nishiki-web-api.yaml
Labels: documentation

#70 change the path of a list of group from "/groups/:userId" to "/…
  web-api/nishiki-web-api.yaml
Labels: documentation

#71 Added an auth me endpoint
  web-api/nishiki-web-api.yaml
Labels: documentation

#73 update get containers endpoint
  web-api/nishiki-web-api.yaml
Labels: documentation

#74 add the aws resource to the project document
  project-document/docs/intro.md
  project-document/docs/system-architecture/functions/main-function.md
  project-document/docs/system-architecture/functions/user-initialize-function.md
  project-document/docs/system-architecture/overview.md
  project-document/sidebars.js
  project-document/static/img/aws/functions/main-function.drawio.svg
  project-document/static/img/aws/resources/Arch_AWS-Lambda_48.svg
  project-document/static/img/aws/resources/Arch_Amazon-API-Gateway_48.svg
  project-document/static/img/aws/resources/Arch_Amazon-Cognito_48.svg
  project-document/static/img/aws/resources/Arch_Amazon-DynamoDB_48.svg
  project-document/static/img/aws/structure.drawio.svg
Labels: documentation

#78 nested a container list into the container object.
  web-api/nishiki-web-api.yaml
Labels: documentation

#80 Added a delete container API
  web-api/nishiki-web-api.yaml
Labels: bug, documentation, enhancement

#82 added an update container name API.
  web-api/nishiki-web-api.yaml
Labels: bug, documentation, enhancement

#88 fixed some status codes
  web-api/nishiki-web-api.yaml
Labels: documentation

#92 Fix woding of join link expiry Datetime
  project-document/docs/database/database.md
Labels: documentation

#85 Delete an SK of the user and group relations
  project-document/docs/database/database.md
Labels: bug, documentation

#69 update DynamoDB definition
  project-document/docs/database/database.md
Labels: documentation

#95 Update join link definition
  project-document/docs/database/database.md
  project-document/docs/database/er-diagram.md
Labels: enhancement

#100 removed the InvitationLinkExpiryDatetime GSI
  project-document/docs/database/database.md
Labels: documentation

#105 doc: add `GroupAndContainerRelationship` GSI
  project-document/docs/database/database.md
Labels: enhancement

#106 Fixed GET /container response data from single container object to multiple container and food object.
  web-api/nishiki-web-api.yaml
Labels: documentation

#108 Added a `GetUser` access pattern
  project-document/docs/database/database.md
Labels: documentation

#115 foods data type
  project-document/docs/database/database.md
Labels: bug, documentation, internal

#124 add how to share container or group specification
  project-document/docs/specifications/detail/invitation-to-group.md
  project-document/docs/specifications/group-and-container.md
  project-document/docs/specifications/terms.md
  project-document/sidebars.js
  project-document/static/img/specification/deleting-group.drawio.svg
  project-document/static/img/specification/deleting-user.drawio.svg
  project-document/static/img/specification/managing-containers.drawio.svg
Labels: documentation
