Repository nishiki-tech/nishiki-documents, pull requests merged in 2024-01, with the labels that each got.

#127 Docs/125 add the web api of a creating hash api
  web-api/nishiki-web-api.yaml
Labels: enhancement, internal

#133 Added a timezone specification
  project-document/docs/specifications/others.md
  project-document/sidebars.js
  web-api/nishiki-web-api.yaml
Labels: documentation, internal

#135 Added the default username specification
  project-document/docs/specifications/terms.md
Labels: documentation

#139 Changed the status code of the joining the group API
  web-api/nishiki-web-api.yaml
Labels: documentation

#140 doc: modified description of endpoints for removing the user from their specific group
  web-api/nishiki-web-api.yaml
Labels: enhancement, internal

#142 Changed the logo of the project document
  project-document/docusaurus.config.js
  project-document/static/img/favicon.ico
  project-document/static/img/nishiki-logo.png
Labels: documentation, internal

#147 Add 403 error to the DELETE /containers/{containerId}/foods/{fo…
  web-api/nishiki-web-api.yaml
Labels: documentation, internal
